version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data/
    env_file:
      - ./.pgadmin.env
    links: 
      - "db:pgsql-server"
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web, pgadmin

volumes:
  postgres_data:
  pgadmin_data: