version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env/.prod.env
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/.db.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data/
    env_file:
      - .env/.pgadmin.env
    links: 
      - "db:pgsql-server"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
      - pgadmin


volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
  media_volume: